name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}
          aws eks --region ap-south-1 update-kubeconfig --name eks
          aws sts get-caller-identity
          cd ~/.aws
          touch config
          echo "[cloud-profile]
                aws_access_key_id = ${{secrets.AWS_ACCESS_KEY_ID}}
                aws_secret_access_key = ${{secrets.AWS_SECRET_ACCESS_KEY}}" > ~/.kube/config

      - name: Install kubectl
        run: |
          sudo apt-get update -q
          sudo apt-get install -y kubectl

      # - name: Set up kubeconfig
      #   run: |
      #     mkdir -p ~/.kube
      #     echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy to EKS
        run: |
          cd helm-charts/quickwage-ewa-production
          helm upgrade ewa-quickwage-backend . -n quickwage-production
