name: Quickwage-webapp-backend-deployment-pipeline

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ${{ secrets.AWS_REGION }}

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ runner.workspace }}/kubeconfig.yaml

      - name: Clone the repo and deploy Helm chart
        run: |
          git clone https://github.com/anshulquickwage/quickwage-devops.git
          cd quickwage-devops/helm-charts/quickwage-ewa-production
          helm upgrade ewa-quickwage-backend . -n quickwage-production
