name: Deploy to EKS

on:
  push:
    branches:
      - release/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Update kube config
        run: aws eks update-kubeconfig --name eks

      - name: Deploy to EKS
        run: |
          cd helm-charts/quickwage-ewa-production
          helm upgrade ewa-quickwage-backend . -n quickwage-production